language: go

go:
    - 1.4.2
    - 1.7.1

before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

script:
    - go vet
    - go test -v -cover -bench .
    - $HOME/gopath/bin/goveralls -service=travis-ci
