version: '3'

services:
    notify:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - mysqld:mysqld
        ports:
            - "8080:8080"
        environment:
            - DATABASE_USER
            - DATABASE_PASS
            - DATABASE
            - DATABASE_DRIVER=mysql
            - AUTH_USER
            - AUTH_PASS
        restart: unless-stopped
    mysqld:
        image: mysql:latest
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=1
            - MYSQL_USER=$DATABASE_USER
            - MYSQL_PASSWORD=$DATABASE_PASS
            - MYSQL_DATABASE=$DATABASE
